CREATE DATABASE IF NOT EXISTS db_article;

CREATE TABLE IF NOT EXISTS posts
(
	Id INT AUTO_INCREMENT,
    Title VARCHAR(200) NOT NULL,
    Content TEXT NOT NULL,
    Category VARCHAR(100) NOT NULL,
    Created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	Updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    Status VARCHAR(100) NOT NULL,
    PRIMARY KEY(Id)
);